config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/auth/facebook', as: 'facebook_login'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  match 'facebooks/index', via: [:get, :post]
  get '/facebooks/login' => 'facebooks#login'
  match 'facebooks/logout', via: [:get, :post]
  match 'facebooks/callback', via: [:get, :post]
  match 'facebooks/menu', via: [:get, :post]
  get 'facebooks/album/:id' => 'facebooks#album', as: 'facebook_album'

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth['provider']
      user.name = auth['info']['name']
      user.uid = auth['uid']
      user.oauth_token = auth['credentials']['token']
      user.oauth_expires_at = Time.at(auth['credentials']['expires_at'])
      user.save!
    end
  end


  def facebook
    # @facebook ||= Koala::Facebook::API.new(oauth_token)
    @facebook ||= FbGraph2::User.me(oauth_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController

  before_action :authenticate_user

  def index
    @albums = current_user.facebook.albums({fields: 'link, name, id'})
  end

  def album
    @photos = FbGraph2::Album.new(album_params[:id]).photos({access_token: current_user.oauth_token, fields: 'id, name, source'})
  end

  def album_params
    params.permit(:id)
  end

  private
  def authenticate_user
    unless current_user
      redirect_to facebook_login_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @facebook_id = ENV['FACEBOOK_KEY']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  protected

  def auth_hash
    params['omniauth.auth'] = env['omniauth.auth']
    (params.require('omniauth.auth').permit!).to_hash.with_indifferent_access
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/facebooks/album.html.erb
<h4>Album page</h4>

<table>
  <thead>
  <td>photo</td>
  <td>photo id</td>
  <td>name</td>
  </thead>
  <tbody>
  <% @photos.each do |photo| %>
      <tr>
        <td><img height="200" width="200" src="<%= photo.source %>" alt="<%= photo.name %>"></td>
        <td><%= link_to photo.id,  photo.source %></td>
        <td><%= photo.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/facebooks/index.html.erb
<h4>Albums</h4>
<table>
  <thead>
  <tr>
    <td>Id</td>
    <td>Name</td>
    <td>Link</td>
  </tr>
  </thead>
  <% @albums.each do |album| %>
      <tr>
        <td><%= album.id %></td>
        <td><%= album.name %></td>
        <td><%= link_to album.name, album.link, class: 'album-link' %></td>
        <td><%= link_to album.name.concat(' - photos'), facebook_album_path(album.id), class: 'album-link' %></td>
      </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<h1>Testing Maps</h1>



<!--<div style='width: 800px;'>-->
  <!--<div id="map" style='width: 800px; height: 400px;'></div>-->
<!--</div>-->


<!--<div style='width: 800px;'>-->
  <!--<div id="custom_builder" style='width: 800px; height: 400px;'></div>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWithMaterialUi</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

  <div id="user_nav">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>
        <%= link_to "Sign out", signout_path, id: 'sign_out' %>
      <% else %>
        <%= link_to "Sign in with facebook", facebook_login_path, id: 'sign_in' %>
      <% end %>
  </div>

  <%= yield %>
</div>

<!--<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>-->
<!--<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>-->
<!--<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> &lt;!&ndash; only if you need custom infoboxes &ndash;&gt;-->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>